version: "3"

networks:
    beware-traefik:
        external: false
        name: beware-traefik

services:
    traefik:
        image: traefik:v2.9
        command: --api.insecure=true --providers.docker
        networks:
            - beware-traefik
        ports:
            - 5000:80
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
        labels:
            - traefik.http.middlewares.auth.forwardauth.address=${NEXTAUTH_URL}/api/auth/middleware/machine
            - traefik.http.middlewares.auth.forwardauth.authRequestHeaders=Cookie
        extra_hosts:
            localhost: host-gateway
