version: "3"

networks:
    beware-traefik:
        external: false
        name: beware-traefik

services:
    traefik:
        image: traefik:v2.9
        restart: always
        command: --api.insecure=true --providers.docker
        networks:
            - beware-traefik
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock:ro
            - ./data/domains:/opt/domains:ro
        labels:
            - traefik.http.middlewares.auth.forwardauth.address=http://nextjs/api/auth/middleware/machine
            - traefik.http.middlewares.auth.forwardauth.authRequestHeaders=Cookie
            - traefik.tls.certificates.0.certfile=/opt/domains/beware.crt
            - traefik.tls.certificates.0.keyfile=/opt/domains/beware.key
            - traefik.tls.certificates.0.stores=default
            - traefik.tls.certificates.1.certfile=/opt/domains/beware-machines.crt
            - traefik.tls.certificates.1.keyfile=/opt/domains/beware-machines.key
        extra_hosts:
            localhost: host-gateway

    mysql:
        image: mysql:8.0
        restart: always
        networks:
            - beware-traefik
        ports:
            - 3306:3306
        environment:
            - MYSQL_ALLOW_EMPTY_PASSWORD=yes
            - MYSQL_DATABASE=beware
            - MYSQL_USER=beware
            - MYSQL_PASSWORD=
        volumes:
            - ./data/mysql:/var/lib/mysql

    nextjs:
        build:
            context: .
            dockerfile: ./apps/nextjs/Dockerfile
            args:
                - NEXT_PUBLIC_MACHINE_URL=https://beware-machines.false-positive.dev
                - DOCKER_PORT=2375
                - DOCKER_HOST=_gateway
                - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
                - NEXTAUTH_URL=https://beware.false-positive.dev
                - EMAIL_SERVER=${EMAIL_SERVER}
                - EMAIL_FROM=${EMAIL_FROM}
                - DATABASE_URL=mysql://beware@mysql:3306/beware
        depends_on:
            - mysql
        restart: always
        networks:
            - beware-traefik
        environment:
            # FIXME: repetition of environment variables
            - NEXT_PUBLIC_MACHINE_URL=https://beware-machines.false-positive.dev
            - DOCKER_PORT=2375
            - DOCKER_HOST=_gateway
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - NEXTAUTH_URL=https://beware.false-positive.dev
            - EMAIL_SERVER=${EMAIL_SERVER}
            - EMAIL_FROM=${EMAIL_FROM}
            - DATABASE_URL=mysql://beware@mysql:3306/beware
        labels:
            - traefik.enable=true
            - traefik.http.routers.nextjs.rule=Host(`beware.false-positive.dev`)
            - traefik.http.services.nextjs.loadbalancer.server.port=3000
